---
name: Get credentials from AWS SSM

on:
  push:
    branches:
      - "master"

jobs:
  get-credentials-from-aws-ssm:
    runs-on: "ubuntu-latest"
    environment: staging3
    env:
      BUILD_STAGE: "staging3"    
    steps:
      # ...

      - uses: "aws-actions/configure-aws-credentials@v1"
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"
          # role-to-assume: "arn:aws:iam::111111111111:role/build-and-deploy-website"
          # role-duration-seconds: 1800 # 30 mins

      - uses: "marvinpinto/action-inject-ssm-secrets@latest"
        with:
          ssm_parameter: "/${{ env.BUILD_STAGE }}/foo"
          env_variable_name: "foo"

      - name: "Build & Deploy"
        run: |
          echo "You will now have access to the FOO environment variable (which is ${{ env.FOO }}) in all your subsequent build steps"